# Generated by Django 4.2.5 on 2023-11-16 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='Id_ingredientes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredientes.ingredientes'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='Id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
